# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('eb_event_id', models.CharField(max_length=40, unique=True)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
